### ISSUE TITLE
Weekly table view

### ISSUE THREAD

**Issue by DarthMikke** [DarthMikke/hourplanner#1]
- [x] #3 Adding an entry
- [x] Displaying entries
- [x] #8 Total worked hours per employee & per day
- [x] Add callback function so that edited entries change total rows & columns of the displayed schedule (#29)

## Bugs to sort out
- [x] #27
