### ISSUE TITLE
Share work plan with employees

### ISSUE THREAD

**Issue by DarthMikke** [DarthMikke/hourplanner#12]
- [ ] Share ID
- [ ] Share model
- [ ] Share access API
- [ ] Share from-to for the whole company
- [ ] Choose which employees' work plan to share

**Comment by DarthMikke** [comment]
Should this be a priority? It would probably be better for the product if an employee would have their own account, and could see their own work plan whenever they wish.
