### ISSUE TITLE
View scheduled work hours

### ISSUE THREAD

**Issue by DarthMikke** [DarthMikke/hourplanner#18]
## Demo
- Log in
- See weekly schedule, grouped by employee

## Tasks
- [x] Enable user login (#24)
- [x] User API (read-only so far) (#13)
- [x] List API (#14)
- [x] Table with employees in the company (#1)
